[workspace]

members = [
    "crates/indexer",
    "crates/stash-api",
    "crates/stash-differ",
    "crates/trade-ingest",
    "crates/trade-api",
    "crates/trade-common",
]

resolver = "1"

[profile.release]
debug = true
