services:
  reverse-proxy:
    image: nginx:latest
    env_file:
      - configuration/environments/.env.development
    volumes:
      - "./configuration/instantiated/reverse-proxy/index.html:/var/www/index.html"
      - "./configuration/instantiated/reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf"
      - "./configuration/instantiated/reverse-proxy/.htpasswd:/etc/nginx/.htpasswd"
    ports:
      - 0.0.0.0:8888:80

  indexer:
    build:
      context: .
      dockerfile: crates/indexer/Dockerfile
      target: development
    env_file:
      - configuration/environments/.env.development
    depends_on:
      - rabbitmq
      - otel-collector
    restart: "always"
    volumes:
      - ".:/app:cached"

  trade-ingest:
    build:
      context: .
      dockerfile: crates/trade-ingest/Dockerfile
      target: development
    depends_on:
      - rabbitmq
      - trade-store
      - otel-collector
    restart: "always"
    env_file:
      - configuration/environments/.env.development
    volumes:
      - ".:/app:cached"

  trade-api:
    build:
      context: .
      dockerfile: crates/trade-api/Dockerfile
      target: development
    depends_on:
      - trade-store
      - otel-collector
    restart: "always"
    env_file:
      - configuration/environments/.env.development
    volumes:
      - ".:/app:cached"

  trade-store:
    image: timescale/timescaledb:2.4.1-pg13
    env_file:
      - configuration/environments/.env.development

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: "always"
    env_file:
      - configuration/environments/.env.development
    environment:
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    volumes:
      - "./configuration/instantiated/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

  otel-collector:
    image: otel/opentelemetry-collector
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./configuration/instantiated/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: "always"
    env_file:
      - configuration/environments/.env.development
