services:
  indexer:
    privileged: true # to enable log forwarding
    image: maximumstock2/indexer:latest
    restart: "always"
    env_file:
      - configuration/environments/.env.production
    environment:
      ENV: "production"
      # disable Postgres sink
      DATABASE_URL:

  trade-api:
    privileged: true # to enable log forwarding
    image: maximumstock2/trade-api:latest
    restart: "always"
    env_file:
      - configuration/environments/.env.production
    environment:
      ENV: "production"

  trade-ingest:
    privileged: true # to enable log forwarding
    image: maximumstock2/trade-ingest:latest
    restart: "always"
    env_file:
      - configuration/environments/.env.production
    environment:
      ENV: "production"

  reverse-proxy:
    privileged: true # to enable log forwarding
    ports:
      - 0.0.0.0:80:80
    env_file:
      - configuration/environments/.env.production

  rabbitmq:
    privileged: true # to enable log forwarding
    env_file:
      - configuration/environments/.env.production

  trade-store:
    privileged: true # to enable log forwarding
    env_file:
      - configuration/environments/.env.production

  jaeger:
    privileged: true # to enable log forwarding
    env_file:
      - configuration/environments/.env.production
