[package]
name = "indexer"
version = "0.1.0"
authors = ["Maximilian Stock <mxmlnstock@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
dotenv = "0.15.0"
chrono = { version = "0.4.38", features = ["serde"] }
stash-api = { path = "../stash-api" }
signal-hook = "0.3.15"
prometheus_exporter = "0.8.5"
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3.28"
tracing = "0.1.38"
trade-common = { path = "../trade-common" }
async-trait = "0.1.80"
lapin = "2.3.4"
aws-sdk-s3 = "1.11.0"
aws-types = "1.3.1"
aws-config = "1.1.1"
aws-credential-types = "1.2.0"
flate2 = "1.0.30"
jsonl = "4.0.1"

[[bin]]
name = "indexer"
path = "src/main.rs"
